import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './css/globals.css'
import { TooltipProvider } from '@/components/ui/tooltip'
import { cn } from '@/lib/utils'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang='en'
            className={cn(
                'h-full',
                'antialiased',
                'font-geist-sans',
                'font-sans',
                roboto.variable
            )}
        >
            <body className='min-h-full flex flex-col'>
                <TooltipProvider>{children}</TooltipProvider>
            </body>
        </html>
    )
}
